---
abstract: 'Natural language processing for English'
author:
  - 'Project Renard'
build_requires:
  List::AllUtils: '0'
  Renard::Block::Format::PDF::Devel::TestHelper: '0'
  Test::Most: '0'
  Test::Needs: '0'
  lib: '0'
  perl: '5.013002'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.013002'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.015, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Renard-Block-NLP
requires:
  Function::Parameters: '0'
  Lingua::EN::Sentence: '0'
  Renard::Incunabula::Common::Setup: '0'
  Renard::Incunabula::Common::Types: '0'
  Text::Unidecode: '0'
  perl: '5.013002'
resources:
  homepage: https://github.com/project-renard/p5-Renard-Block-NLP
  repository: https://github.com/project-renard/p5-Renard-Block-NLP.git
version: '0.001'
x_generated_by_perl: v5.26.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
